# Generated by Django 5.1.4 on 2024-12-28 19:18

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.AutoField(help_text='Уникальный ID для торта', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Название торта', max_length=100, verbose_name='Название')),
                ('weight', models.IntegerField(help_text='Вес торта в граммах', verbose_name='Вес')),
                ('description', models.TextField(help_text='Описание торта', max_length=1000, verbose_name='Описание')),
                ('image', models.CharField(help_text='Изображение торта', max_length=100, verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена торта в руб.', max_digits=10, verbose_name='Цена')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(help_text='Уникальный ID для ингредиента', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Название ингредиента', max_length=100, verbose_name='Название')),
                ('units', models.CharField(help_text='Наименование единиц измерения', max_length=10, verbose_name='Единицы измерения')),
                ('count', models.IntegerField(help_text='Количество ингредиента', verbose_name='Количество')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(help_text='Пользователь, владеющий корзиной', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeshop.cake', verbose_name='Торт')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cakeshop.cart', verbose_name='Корзина')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCake',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True, help_text='Уникальный ID для торта')),
                ('title', models.CharField(help_text='Название торта', max_length=100, verbose_name='Название')),
                ('weight', models.IntegerField(help_text='Вес торта в граммах', verbose_name='Вес')),
                ('description', models.TextField(help_text='Описание торта', max_length=1000, verbose_name='Описание')),
                ('image', models.CharField(help_text='Изображение торта', max_length=100, verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена торта в руб.', max_digits=10, verbose_name='Цена')),
                ('created_at', models.DateField(blank=True, editable=False, verbose_name='Дата создания')),
                ('updated_at', models.DateField(blank=True, editable=False, verbose_name='Дата обновления')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical cake',
                'verbose_name_plural': 'historical cakes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIngredient',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True, help_text='Уникальный ID для ингредиента')),
                ('title', models.CharField(help_text='Название ингредиента', max_length=100, verbose_name='Название')),
                ('units', models.CharField(help_text='Наименование единиц измерения', max_length=10, verbose_name='Единицы измерения')),
                ('count', models.IntegerField(help_text='Количество ингредиента', verbose_name='Количество')),
                ('created_at', models.DateField(blank=True, editable=False, verbose_name='Дата создания')),
                ('updated_at', models.DateField(blank=True, editable=False, verbose_name='Дата обновления')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical ingredient',
                'verbose_name_plural': 'historical ingredients',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='cake',
            name='ingredients',
            field=models.ManyToManyField(blank=True, help_text='Ингредиенты используемые для приготовления', to='cakeshop.ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_date', models.DateField(help_text='Дата доставки заказа клиенту', verbose_name='Дата доставки')),
                ('status', models.CharField(choices=[('О', 'Ожидается'), ('З', 'Завершён')], help_text='Статус заказа', max_length=1, verbose_name='Статус')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Общая стоимость заказа', max_digits=10, verbose_name='Стоимость')),
                ('delivery_address', models.CharField(help_text='Адрес, по которому доставляется заказ', max_length=255, verbose_name='Адрес доставки')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeshop.cake', verbose_name='Торт')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeshop.order', verbose_name='Заказ')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='cakes',
            field=models.ManyToManyField(help_text='Торты добавленные в заказ', through='cakeshop.OrderCake', to='cakeshop.cake', verbose_name='Торты'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.IntegerField(auto_created=True, help_text='Уникальный ID для отзыва', primary_key=True, serialize=False)),
                ('review', models.TextField(help_text='Текст отзыва', max_length=1000, verbose_name='Отзыв')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('cake', models.ForeignKey(help_text='Торт, на который оставили отзыв', on_delete=django.db.models.deletion.CASCADE, to='cakeshop.cake', verbose_name='Торт')),
                ('user', models.ForeignKey(help_text='Пользователь, оставивший отзыв', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['cake'],
            },
        ),
    ]
