# Generated by Django 5.0.6 on 2024-12-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='id',
            field=models.IntegerField(auto_created=True, help_text='Уникальный ID для торта', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.IntegerField(auto_created=True, help_text='Уникальный ID для ингредиента', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.IntegerField(auto_created=True, help_text='Уникальный ID для заказа', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ordercake',
            name='id',
            field=models.IntegerField(auto_created=True, help_text='Уникальный ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.IntegerField(auto_created=True, help_text='Уникальный ID для отзыва', primary_key=True, serialize=False),
        ),
    ]
