# Generated by Django 5.0.6 on 2024-12-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeshop', '0002_alter_cake_id_alter_ingredient_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='image',
            field=models.CharField(help_text='Изображение торта', max_length=100, verbose_name='Изображение'),
        ),
    ]
