# Generated by Django 5.0.6 on 2024-12-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeshop', '0004_ordercake_quantity_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercake',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
